/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_SudokuActivity */

#ifndef _Included_com_example_androidex_SudokuActivity
#define _Included_com_example_androidex_SudokuActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_SudokuActivity
 * Method:    readKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_SudokuActivity_readKey
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androidex_SudokuActivity
 * Method:    readSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_SudokuActivity_readSwitch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
